/*
auto-generated by: https://github.com/react-spring/gltfjsx
author: Artur Coelho (https://sketchfab.com/coelhoelectrico)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tree-roots-fdf4ecb9165c4e778cf0590332380a0b
title: Tree roots
*/

// import * as THREE from 'three'
import React from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export default function RootModel(props) {
  const { nodes, materials } = useLoader(GLTFLoader, '/models/root/scene.gltf')
  return (
    <mesh
      material={materials.material_0}
      castShadow
      receiveShadow
      rotation={[-Math.PI / 2, 0, 0]}
      {...props}
    >
      <primitive attach="geometry" object={nodes.mesh_0.geometry} />
    </mesh>
  )
}
